[default]
mongo_uri = "mongodb+srv://mongo:SJjtxZ2MdybhP5no@study.emtthmt.mongodb.net/blog?retryWrites=true&w=majority"
title = "Blog"
secret_key = "64cce1fce82ec4c9c4d026c7dea728e4b78366997b8073bcea5708752872d2c3"
EXTENSIONS = [
    "blog.database:configure",
    "blog.commands:configure",
    "flask_bootstrap:Bootstrap",
    "blog.views:configure",
    "blog.plugins:configure",
    "blog.auth:configure",

]